config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, :only => [:show] do
    resources :consumptions
  end


  resources :foods, :only => [:index, :new, :create]

  root :to => "foods#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consumption.rb
class Consumption < ActiveRecord::Base
  validates :meal, :user_id, :servings, :food_id, :presence => true
  belongs_to :user
  belongs_to :food
  before_save :calculate_calories

private
  def calculate_calories
    food = Food.find(self.food_id)
    self.calories = (self.servings * food.calories_per_serving)
  end
end

app/models/food.rb
class Food < ActiveRecord::Base
  has_many :consumptions
  validates :name, :calories_per_serving, :serving_size, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :consumptions
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def after_sign_in_path_for(user)
    user_path(user)
  end
end

app/controllers/consumptions_controller.rb
class ConsumptionsController < ApplicationController
  def create
    @user = current_user
    @todays_consumptions = @user.consumptions.where("created_at::date =?", Date.today)
    @consumption = Consumption.new(consumption_params)
    if @consumption.save
      flash[:notice] = "Food saved!"
      respond_to do |format|
        format.html {redirect_to user_path(current_user)}
        format.js
      end
    else
      flash[:alert] = "Whoops, try again."
      redirect_to user_path(@user)
    end
  end

private
  def consumption_params
    params.require(:consumption).permit(:meal, :user_id, :food_id, :servings)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def new
    @food = Food.new
  end

  def create
    @foods = Food.all
    @food = Food.new(food_params)
    if @food.save

      respond_to do |format|
        format.html {redirect_to user_path(current_user)}
        format.js { flash[:notice] = "Food added to the database!"}
      end
    else
      flash[:alert] = "There was a problem adding your food, please try again"
      redirect_to user_path(current_user)
    end
  end

  private
  def food_params
    params.require(:food).permit(:name, :calories_per_serving, :serving_size)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
    @todays_consumptions = @user.consumptions.where("created_at::date =?", Date.today)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/consumptions/_form.html.erb
<div id="add_consumption_form">
  <%= form_for [@user, @consumption], remote: true do |f| %>
    <h3>Add to your eaten foods:</h3>
    <%= f.label :food_id %>
    <%= f.collection_select(:food_id, @foods, :id, :name, {}, {class: "form-control"}) %>
    <% options = ([['Breakfast', 'Breakfast'], ['Lunch', 'Lunch'], ['Dinner', 'Dinner'], ['Snack', 'Snack']]) %>
    <%= f.label :meal %>
    <%= f.select(:meal, options_for_select(options), {}, {class: "form-control"})  %>
    <%= f.label :servings %>
    <%= f.select(:servings, options_for_select((1..10)), {}, {class: "form-control"})  %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/consumptions/create.js.erb
$('#eaten_foods_list').append("<li><%=@consumption.food.name%>, <%=@consumption.calories%> calories</li>");
$('#todays_cals').html("<%= @todays_consumptions.sum(:calories) %>");

new Chartkick.ColumnChart('chart-1', [["Calories", <%=@todays_consumptions.sum(:calories)%>]], {'min': 0, "max": 2000, 'height': '500px', 'width': '600px'});

app/views/foods/_new.html.erb
<div class="col-sm-6 col-sm-offset-3">
  <%= form_for @food, html: {id: :add_food_form}, remote: true do |f| %>
    <h2>Add a food item to the database</h2>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
    <%= f.label :calories_per_serving %>
    <%= f.text_field :calories_per_serving, class: "form-control" %>
    <%= f.label :serving_size %>
    <%= f.text_field :serving_size, class: "form-control" %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/foods/create.js.erb
$('#add_food_form').remove();
$('#add_food_link').show();
var food_options = $('#consumption_food_id');
food_options.empty();

<% @foods.each do |f| %>
  food_options.append("<option value='<%=f.id%>'> <%=f.name%> </option>");
<% end %>

app/views/foods/index.html.erb
<h3>Here are some foods available in our app:</h3>
<% if @foods.any? %>
<ul class="list-group">
  <% @foods.each do |food| %>
    <li class="list-group-item"><%= food.name %></li>
  <% end %>
</ul>
<% else %>
  <p> No foods yet. </p>
<% end %>

app/views/foods/new.html.erb
<h2>Add a food item to the database</h2>

<%= form_for @food do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :calories_per_serving %>
  <%= f.text_field :calories_per_serving %>
  <%= f.label :serving_size %>
  <%= f.text_field :serving_size %>
  <%= f.submit %>
<% end %>

app/views/foods/new.js.erb
$('#add_food_link').hide().after('<%= j render("foods/new") %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthTracker</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-6">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <ul class="nav navbar-nav">
            <li><%= link_to "Health Tracker", foods_path, class: "navbar-brand" %></li>
          </ul>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-6">
          <ul class="nav navbar-nav">
            <% if current_user %>
              <li class="nav-item"><%= link_to "Logout", destroy_user_session_path, :method => "delete" %></li>
              <li class="nav-item"><%= link_to "My Profile", user_path(current_user.id) %></li>
            <% else %>
              <li class="nav-item"><%= link_to "Login", new_user_session_path %></li>
              <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
         </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
      <div class="push-down container">
        <% if flash[:notice] %>
          <div class="alert alert-info push-down">
            <%= flash[:notice] %>
          </div>
        <% end %>
        <% if flash[:alert] %>
          <div class="alert alert-danger push-down">
            <%= flash[:alert] %>
          </div>
          <% end %>
      </div>

      <div class="push-down container">
        <%= yield %>
      </div>

      <footer class="footer">
        <div class="text-muted">
          <br><p>&copy; 2016 Matt Carlson and Molly McGlone</p>
        </div>
      </footer>
  </body>
</html>

app/views/users/_column_chart.html.erb
<% data = {"Calories" => @todays_consumptions.sum(:calories)} %>
<%= column_chart data, discrete: true, min: 0, max: 2000, width: "600px", height: "500px" %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="col-sm-8 col-sm-offset-2">
  <h1 class="center"> <%= @user.email %>'s Profile
  <h3 class="center"> Your daily calories goal: 2,000 calories</h3>
  <h3 class="center"> You've currently consumed: <span id="todays_cals"><%= @todays_consumptions.sum(:calories) %></span>  calories</h3>
</div>

<div class="col-sm-8 col-sm-offset-2">
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

  <%= render :partial => 'column_chart', :object => @todays_consumptions %>
</div>

<div class="row">
  <div class="col-sm-6">
    <h3> Here's what you've eaten today: </h3>
    <ul id = "eaten_foods_list">
      <% if @todays_consumptions.any? %>
        <% @todays_consumptions.each do |consumption| %>
          <li> <%= consumption.food.name %>, <%= consumption.calories %> calories</li>
        <% end %>
      <% else %>
        <p>You haven't eaten anything today!</p>
      <% end %>
    </ul>
  </div>
  <div class="col-sm-6">
    <%= render :partial => 'consumptions/form', locals: {:@user => @user, :@consumption => @user.consumptions.new, :@foods => Food.all }%>
  </div>
</div>
<div class="row">
  <div class="col-sm-4 col-sm-offset-4" id="add_food_link">
    <h4><%= link_to "Add a new food to the database", new_food_path, remote: true, class: "btn btn-warning btn-block" %><h4>
  </div>
</div>